export const ADD_TASCK='ADD TASCK'
export const DELETE_TASCK='delete tASCK'
export const FILTER_DONE_TASCK ='filter done tasck'
export const FILTER_UNDONE_TASCK ='filter undone tasck'
export const EDIT_TASCK ='EDIT TASCK'
export const CHECK_DONE_TASCK='check done tasck'